learning_django_app/learning_django_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

learning_django_app/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>', views.detail, name='detail'),
    path('<int:question_id>/results', views.results, name='results'),
]

learning_django_app/polls/models.py
from django.db import models

# Create your models here.


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    # on_delete=models.CASCADE: if question is deleted all of it choices will also be deleted
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

learning_django_app/polls/views.py
from django.shortcuts import render, Http404, get_object_or_404

# Create your views here.


from .models import Question, Choice


# Get questions and display them
def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)


def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question Does Not Exist")
    return render(request, 'polls/detail.html', {'question': question})


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

learning_django_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Pollster {% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-6 m-auto">
            {% block content %}

            {% endblock %}
        </div>
    </div>
</div>
</body>
</html>

learning_django_app/templates/partials/_navbar.html
<nav>

</nav>

learning_django_app/templates/polls/detail.html
{% extends 'base.html' %}


{% block content %}
    {% csrf_token %}


{% endblock %}

learning_django_app/templates/polls/index.html
{% extends 'base.html' %}

{% block content %}

    <h1>Polls</h1>
    {% if latest_question_list %}
        {% for question in latest_question_list %}
            <div class="card md-3">
                <div class="card-body">
                    <p class="lead">
                        {{ question.question_text }}
                    </p>
                    <a href="{% url 'polls:detail' question.id %}" class="btn btn-primary btn-sm">Vote Now</a>
                    <a href="{% url 'polls:results' question.id %}" class="btn btn-primary btn-sm">Results</a>

                </div>
            </div>
        {% endfor %}
    {% else %}
        <p>No pools</p>
    {% endif %}

{% endblock %}

learning_django_app/templates/polls/results.html
{% extends 'base.html' %}


{% block content %}
    {% csrf_token %}

    
{% endblock %}